### PR TITLE
Remove unused SVN (svn_url) property from .data.json and webpage

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by bdrewery** [comment]
It's unused for FreeBSD.org but it is not unused for Poudriere. Poudriere still supports local SVN repositories and would populate this field.

It would make sense to _hide_ the field if there is no value set in the json.

**Comment by michael-o** [comment]
Well, it does not really cover all cases, e.g., FreeBSD ports from Git and my overlays from Subversion. I'd rather not have any information instead of incomplete or wrong information.

**Comment by bdrewery** [comment]
Overlays were not a complete feature and were just hacked on. Come to think of it, the web ui should learn to show each overlay that is used and the metadata from each.

**Comment by michael-o** [comment]
Then this node needs to be renamed and tuned into a list.

**Comment by bdrewery** [comment]
Moved to #1024

**Pull request closed without merging**
