### PR TITLE
Shush make by default in jail command

### PR DESCRIPTION
**Pull request by grimreaper**
poudriere can generate a lot of output, so try and keep it quieter in normal case

### CODE REVIEW

**Comment by mat813** [comment]
Why?

I don't really think this is a good idea.

**Comment by grimreaper** [comment]
Most of the time when using poudriere you've already built the code at least once. Even if not, its quite common to using `-s` for the first build.

when doing tasks like:
```
[00:00:00] Copying /usr/src to /poudriere/jails/amd64-matches-host/usr/src... done
```
seeing all the `rm -f` and `install` commands is just noise. make(1) already tells you what its done if something went wrong.

**Comment by bdrewery** [comment]
Make does not show the failing command on a build failure with `-s`. This is critical debugging information. Too bad we used `-v` in `jail` already or this could be gated on `VERBOSE` from the standard `-v`.

**Comment by mat813** [comment]
What do you mean "you've already built the code at least once"?
I always build everything inside poudriere, so, if poudriere never shows me what it is doing, how can I see what is happening?

**Comment by grimreaper** [comment]
> What do you mean "you've already built the code at least once"?
There are three possible cases:
(a) you've already built and now you're just installing (-b)
(b) you've already built, and you rebuild for poudriere (-b, but you have tested previously)
(c) the first time you're building the tree is for poudriere.

I suspect for most people (c) is far less common. Even when portmgr tests a patch, hopefully the provider of the patch has already tested it at least once.
For cases (a) and (b) poduriere produces excessive output which makes following the logs harder, and possibly slows down the update.

**Comment by bdrewery** [comment]
As is this won't be taken as it is critical to see the build output somewhere for debugging failures.

**Pull request closed without merging**
