### PR TITLE
add option to delete portstree when created with -F

### PR DESCRIPTION
**Pull request by danel1**
When creating a portstree with the following options:
"poudriere ports -c -F -p name"
everything get's created correctly and the zfs is also made.
But since the following two commit's, it's inpossible to delete the portstree with poudriere. The only way would be to delete and clean up everything by hand, which is not a nice way and the way you want to do it.

See:
https://github.com/freebsd/poudriere/commit/ba02294a1f4aacc3f54e544178c92628c8e4b7f6
and
https://github.com/freebsd/poudriere/commit/7ca6e58de9958eb70c72825a62438d9ed8d3bead

### CODE REVIEW

**Comment by bdrewery** [comment]
Thanks for the patch. I'm not fond of another flag here. The root problem is that `-F` does something and never records the fact that it did it. If `-F` was used (without method `-` or `none`) then it needs to automatically clean up.

There's far too many flags and options here. `-m none` and `-f none` do totally different things, and `-F` is a hack.

Looking over this more, it seems that using `-F` will actually record the method as `-`, so 7ca6e58de9958eb70c72825a62438d9ed8d3bead may just need to be reverted instead.

**Comment by bdrewery** [comment]
For reference, further discussion at ba02294a1f4aacc3f54e544178c92628c8e4b7f6.

**Comment by danel1** [comment]
True, i just tought this would also be a fast way to patch this, instead of completely rewrite the ports.sh-Script.. :-) But indeed, if a portstree is created with "-F", it always uses method "-". So reverting 7ca6e58 would be the most simple and "best" option until we find a better solution, i think.

**Comment by bdrewery** [comment]
I missed saying it, but I am tempted to rip out all of this obscure stuff and simply the interface. And then add stubs to disallow the old ones.

**Comment by danel1** [comment]
Thanks for adding the milestone @bdrewery! I hope you can fix this in 3.1.20. Have a good day

**Comment by bdrewery** [comment]
Yup I am going to take a fresh look at it in the next week.

**Comment by bdrewery** [comment]
This is fixed for newly-created trees after these fixes.

**Comment by danel1** [comment]
Thanks :) Will take a look at it and test when the new version will be released.
Do you have a timeline when you plan to release 3.1.20?

**Pull request closed without merging**
