### PR TITLE
Speed up tar creation by using xz -T 0

### PR DESCRIPTION
**Pull request by swills**

### CODE REVIEW

**Comment by swills** [comment]
Not sure if you will like this idea or not, but it definitely speeds up tar creation for me. If you would rather this were optional, I can change it.

**Comment by reezer** [comment]
Do you think piping from tar to xz instead of creating, writing to disk, compressing and then moving would make sense in order to decrease disk IO?

**Comment by swills** [comment]
@reezer Yeah, good point, I probably should do that instead. I'll revise.

**Comment by bdrewery** [comment]
Fine with me, @bapt @brd @evadot any feedback? I don't touch this file.

**Comment by bapt** [comment]
fine to me

**Comment by evadot** [comment]
fine with me too.

**Comment by brd** [comment]
Merged, thanks!

Sorry it took so long, I forgot about this.

**Pull request closed without merging**
