### PR TITLE
Redesign Poudriere web dashboard along with updating Bootstrap 3 to Bootstrap 5

### PR DESCRIPTION
**Pull request by fel1x-developer**
Screenshot 2024-01-18 at 17 46 45
Screenshot 2024-01-18 at 17 46 48
Screenshot 2024-01-18 at 17 46 54

### CODE REVIEW

**Comment by igalic** [comment]
could you also add some before pictures for comparison?

**Comment by fel1x-developer** [comment]
> could you also add some before pictures for comparison?


Screenshot 2024-01-01 at 13 01 45
Screenshot 2024-01-01 at 13 01 59
Screenshot 2024-01-01 at 13 02 11

**Comment by fel1x-developer** [comment]
**TODOs**

CSS

- Improve table styles
- Improve build progress table

Javascript

- Fix old syntax (e.g. `var`->`let, const`)
- Replace `svn_url` with `git_url`

We might need to introduce web frameworks like React or Vue because maintaining the web app is now extremely difficult with vanilla Javascript + jQuery.

I would appreciate if you could add these lists to Projects.

**Comment by fel1x-developer** [comment]
Steps for redesigning and migrating to Bootstrap 5 are now done and ready to be reviewed.

**Comment by bapt** [comment]
I love it! thank you, I will review ASAP

**Comment by fel1x-developer** [comment]
Hi! Just a reminder that the [beta version of jQuery 4](https://github.com/jquery/jquery/releases/tag/4.0.0-beta) is out. I am ready to create pull request once this PR is merged to the main branch.

**Comment by bdrewery** [comment]
This was merged already wasn't it?

**Comment by bdrewery** [comment]
The PR was manually merged before so I manually cherry-picked those 3 commits just now. It's all in. Thank you for this. It's awesome. 
Please open a new PR for further updates.

**Pull request closed without merging**
