### PR TITLE
Allow to disable grepping logs for failure reason

### PR DESCRIPTION
**Pull request by AMDmi3**
This takes a lot of time for no usable result in most cases

### CODE REVIEW

**Comment by bdrewery** [comment]
I think this is fine but I'm curious if you have seen measurable improvements with disabling this?

**Comment by swills** [comment]
For me, it can take literally hours to run processonelog.sh on some larger log files, so I would really like this change.

**Comment by AMDmi3** [comment]
I occasionally run into ports which generate huge logs, and grepping after a failure may take a few dozen of seconds on them. This is terribly annoying for change→test→repeat workflow (and I don't even see the result after testport). I don't remember specific ports to demonstrate this, unfortunately.

**Comment by bdrewery** [comment]
> This is terribly annoying for change→test→repeat workflow (and I don't even see the result after testport).

That's an excellent point. This could be moved off to an asynchronous job too. I'll merge in what you have for now.

**Comment by AMDmi3** [comment]
>  I'll merge in what you have for now.

I'd :+1: that, but you seem to be blocking me for some reason.

**Comment by clausecker** [comment]
Same issue here.  When a larger port (e.g. `qt5-webkit`) fails due to an OOM condition, a 60M+ log file is created.  Analysing the error cause takes more than an hour due to `grep` calls that take more than 20 minutes each.  I'm running Poudriere on a Raspberry Pi 4B+ running arm64 FreeBSD 13.

**Pull request merged**
