### PR TITLE
Add -K

### PR DESCRIPTION
**Pull request by pgollucci**
kills the jail specified in -j jail_name if its running
by calling jail_stop()

### CODE REVIEW

**Comment by bdrewery** [comment]
This is what jail -k already does. Why do you think testport needs it too?

Regards,
Bryan Drewery

**Comment by pgollucci** [comment]
A typical workflow for me is:

# sudo $_poudriere bulk -t -j $build -B $B -s -C $what
while 'needed'; do
 # sudo $_poudriere testport -K -j $build -o $port -I -s
 # sudo jexec ${build}-default-n env -i TERM=$TERM /usr/bin/login -fp root
 # exit
done

If you allow -K here, I don't have to run an additional command after the
 exit to kill it or before the testport to kill it

Call me lazy ?




On Tue, Jul 7, 2015 at 11:53 PM, Bryan Drewery <notifications@github.com>
wrote:

> This is what jail -k already does. Why do you think testport needs it too?
>
> Regards,
> Bryan Drewery
>
> > On Jul 7, 2015, at 18:39, Philip M. Gollucci <notifications@github.com>
> wrote:
> >
> > kills the jail specified in -j jail_name if its running
> > by calling jail_stop()
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/freebsd/poudriere/pull/327
> >
> > Commit Summary
> >
> > Add -K
> > File Changes
> >
> > M src/share/poudriere/testport.sh (8)
> > Patch Links:
> >
> > https://github.com/freebsd/poudriere/pull/327.patch
> > https://github.com/freebsd/poudriere/pull/327.diff
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freebsd/poudriere/pull/327#issuecomment-119415640>.
>



-- 
---------------------------------------------------------------------------------
Curb: Your ride is here
4096R/D21D2752
<http://pgp.mit.edu/pks/lookup?op=get&search=0xF699A450D21D2752> ECDF B597
B54B 7F92 753E  E0EA F699 A450 D21D 2752
Philip M. Gollucci (pgollucci@p6m7g8.com) c: 703.336.9354
Member,                           Apache Software Foundation
Committer,                        FreeBSD Foundation
Consultant,                       P6M7G8 Inc.
Sr. Director IT Operations,       Curb

What doesn't kill us can only make us stronger;
Except it almost kills you.

**Comment by brd** [comment]
You probably want to use ```testport -i``` instead of ```testport -I; jexec```?

**Comment by bdrewery** [comment]
Yup

**Comment by pgollucci** [comment]
mumble.  you're right I'm blind.

**Comment by brd** [comment]
:)

**Pull request closed without merging**
